apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module3-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sadyplabon/Module-3-deployment.git
    targetRevision: main
    path: k8s/canary
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

